spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentDB?createDatabaseIfNotExist=true
    username: postgres
    password: admin
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

